export default {
  port: process.env.PORT || 5000,
  mongoUri: process.env.MONGO_URI,
  sendgridApiKey: process.env.SENDGRID_API_KEY || '',
  fromEmail: process.env.FROM_EMAIL || '',
  toEmail: process.env.TO_EMAIL || '',
  publicKey: process.env.PUBLIC_KEY || '',
  privateKey: process.env.PRIVATE_KEY || '',
  logoAddress: process.env.LOGO_ADDRESS || '',
  addressServer: process.env.ADDRESS_SERVER || '',
  keys: ['dfkjndsnd', 'asbjbs'],
  redisServer: process.env.REDIS_ADDRESS || '',
  cloudinaryCloudName: process.env.CLOUDINARY_CLOUD_NAME || '',
  cloudinaryApiKey: process.env.CLOUDINARY_API_KEY || '',
  cloudinaryApiSecret: process.env.CLOUDINARY_API_SECRET || '',
  cors: process.env.CORS || '*',
  cookieDomain: process.env.COOKIE_DOMAIN || 'localhost',
  enterpriseName: process.env.ENTERPRISE_NAME || '',
};
